name: Continuous Testing
run-name: ${{github.actor}} is testing out this project
on: push
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "$PWD"
      - run: pip3 install black
      - run: pip3 install mypy
      - run: black \app.py
      - run: mypy app.py
