name: Continuous Testing
run-name: ${{github.actor}} is testing out this project
on: push
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: black .
      - run: mypy .
